require:
  - rubocop-rails

AllCops:
  Exclude:
    - "db/**/*"
    - "vendor/**/*"
    - "lib/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "Gemfile"
    - "Rakefile"
    - "config.ru"
  NewCops: enable

Style/Documentation:
  Enabled: false
