version: 2.1
aliases:
  - &exectuor_ruby
    image: circleci/ruby:3.0.0
    environment:
      RAILS_ENV: test
      TERM: dumb
  - &setup_bundler
    run:
      name: setup bundler
      command: |
        gem install bundler
        bundle config --local path 'vendor/bundle'
        bundle config --local jobs 20
        bundle config --local frozen true    
  - &restore_cache
    restore_cache:
      keys:
        - sandbox-app-bundle-{{ checksum "Gemfile.lock" }}
        - sandbox-app-bundle-
  - &save_cache
    save_cache:
      key: sandbox-app-bundle-{{ checksum "Gemfile.lock" }}
      paths: 
        - vendor/bundle        
executors:
  ruby:
    docker:
      - *exectuor_ruby
  ruby_with_db:
    docker:
      - *exectuor_ruby
      - image: circleci/postgres:11.9-ram
        environment:
          POSTGRES_USER: sandbox
          POSTGRES_PASSWORD: sandbox
jobs:
  bundler:
    executor: ruby
    steps:
      - checkout
      - *restore_cache
      - *setup_bundler
      - run:
          name: install dependencies
          command: |
            bundle install
      - *save_cache
  rubocop:
    executor: ruby
    steps:
      - checkout
      - *restore_cache
      - *setup_bundler
      - run:
          name: rubocop
          command: |
            bundle exec rubocop
  rspec:
    executor: ruby_with_db
    steps:
      - checkout
      - *restore_cache
      - *setup_bundler
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - run:
          name: rspec
          command: |
            bundle exec rails db:setup
            bundle exec rspec
workflows:
  version: 2
  test:
    jobs:
      - bundler
      - rubocop:
          requires:
            - bundler
      - rspec:
          requires:
            - bundler
